#! /usr/bin/env python3

import os
import socket
import sys

selector = ""
host = ""
port = 70
clrf = "\r\n"

def request():
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((host, port))
    s.send("\r\n".encode("utf-8"))
    s.shutdown(1)
    return s.makefile("r")

def view():
    content = []
    page = request().read().split("\n")

    for line in page:
        if (not line) or (line[0] == "."):
            continue
        else:
            linetype = line[0]
            parts= line[1:].split("\t")
            parts.insert(0, linetype)
            content.append(parts)
    for line in content:
        print(line)

def cgob():
    global host

    if (host):
        view()

    while(True):
        prompt = input("> ")
        if (prompt == "q"):
            sys.exit()
        elif (prompt == "g"):
            host = input("hostname > ")
            view()
        else:
            print("?")

def main():
    global host

    args = sys.argv

    if (len(args) == 2):
        host = args[1]

    cgob()

if (__name__ == "__main__"):
    main()
